# Welcome to Jekyll!

# Website settings
title: "MA"
description: "MA's blog,use Jekyll and github pages."
keywords: "MA,Mohammed,portfolio,blog,Jekyll,github,gh-pages"
baseurl: "/"
#url: "http://127.0.0.1:4000"
url: "http://muhammedgit.github.io"

# author
author:
  name: 'Mohammed'
  first_name: 'Mohammed'
  last_name: 'Alayyoub'
  email: 'muhammedalayyoubb@gmail.com'
  github_username: 'MuhammedGit'
  head_img: 'static/img/landing/Mohammed.jpg'
  desc: 'I am a Software Engineer with Masters degree. I like to learn new stuff since to me life is a continuous learning process, so work makes me more rigorous. My career objective is to improve myself in every way I can and to have all the needs of a job that
gives me pleasure.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career2'
    i18n: 'nav.career2'
    name: 'Career'
    tpl: 'career2.html'
    css: 'timeline'
    
  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'
 
  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'
    

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'zh'
    flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://muhammedgit.github.io/static/img/blog'


# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
